/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as PatrolsRouteImport } from './routes/patrols'
import { Route as NfcScansRouteImport } from './routes/nfc-scans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrolsRoute = PatrolsRouteImport.update({
  id: '/patrols',
  path: '/patrols',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcScansRoute = NfcScansRouteImport.update({
  id: '/nfc-scans',
  path: '/nfc-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/nfc-scans': typeof NfcScansRoute
  '/patrols': typeof PatrolsRoute
  '/shifts': typeof ShiftsRoute
  '/sites': typeof SitesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/nfc-scans': typeof NfcScansRoute
  '/patrols': typeof PatrolsRoute
  '/shifts': typeof ShiftsRoute
  '/sites': typeof SitesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/nfc-scans': typeof NfcScansRoute
  '/patrols': typeof PatrolsRoute
  '/shifts': typeof ShiftsRoute
  '/sites': typeof SitesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/nfc-scans'
    | '/patrols'
    | '/shifts'
    | '/sites'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/nfc-scans'
    | '/patrols'
    | '/shifts'
    | '/sites'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/incidents'
    | '/login'
    | '/nfc-scans'
    | '/patrols'
    | '/shifts'
    | '/sites'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IncidentsRoute: typeof IncidentsRoute
  LoginRoute: typeof LoginRoute
  NfcScansRoute: typeof NfcScansRoute
  PatrolsRoute: typeof PatrolsRoute
  ShiftsRoute: typeof ShiftsRoute
  SitesRoute: typeof SitesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrols': {
      id: '/patrols'
      path: '/patrols'
      fullPath: '/patrols'
      preLoaderRoute: typeof PatrolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-scans': {
      id: '/nfc-scans'
      path: '/nfc-scans'
      fullPath: '/nfc-scans'
      preLoaderRoute: typeof NfcScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IncidentsRoute: IncidentsRoute,
  LoginRoute: LoginRoute,
  NfcScansRoute: NfcScansRoute,
  PatrolsRoute: PatrolsRoute,
  ShiftsRoute: ShiftsRoute,
  SitesRoute: SitesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
